controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

user_dashboard:
    path: /user/dashboard
    controller: App\Controller\UserController::dashboard